// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OkulYönetimAPI.DataAccess;

#nullable disable

namespace OkulYönetimAPI.DataAccess.Migrations
{
    [DbContext(typeof(SchoolDBContext))]
    [Migration("20230926075111_mig_postgresql_createdatabase")]
    partial class mig_postgresql_createdatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OkulYönetimAPI.Entity.Lessons", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("lessons")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("Lessons");
                });

            modelBuilder.Entity("OkulYönetimAPI.Entity.Schools", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("schooladress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("schoolname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("schoolphone")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.ToTable("Schools");
                });

            modelBuilder.Entity("OkulYönetimAPI.Entity.Students", b =>
                {
                    b.Property<int>("ıd")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ıd"));

                    b.Property<int>("IdentıtyNumber")
                        .HasColumnType("integer");

                    b.Property<int>("StudentsPassword")
                        .HasColumnType("integer");

                    b.Property<string>("aappointedteachers")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("examnotes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("homeworks")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("studentname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("studentnumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("studentschool")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("studentsclassnumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("studentslevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("studentsurname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ıd");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("OkulYönetimAPI.Entity.Teachers", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("teacheralan")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("teachername")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("teachernumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("teacherpermissions")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("teachersurname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("Teachers");
                });
#pragma warning restore 612, 618
        }
    }
}
